

import { SimulationParameters } from './types';

export const MOCK_CODE_AWK = `
# AWK script for post-processing simulation trace files generated by a C++ simulator like NS-3.
# This script parses trace data to calculate key performance metrics.
# ---
# AWK script to calculate Packet Delivery Ratio (PDR)
BEGIN {
    sent_packets = 0;
    received_packets = 0;
    start_time = -1;
    end_time = -1;
}

# For each line in the trace file
{
    event = $1;
    time = $2;
    packet_id = $6;

    if (start_time < 0) {
      start_time = time;
    }
    end_time = time;

    if (event == "+") { # enqueued
        sent_packets++;
    }
    if (event == "r") { # received
        received_packets++;
    }
}

END {
    simulation_time = end_time - start_time;
    if (sent_packets > 0) {
        pdr = (received_packets / sent_packets) * 100;
        printf "Total Packets Sent: %d\\n", sent_packets;
        printf "Total Packets Received: %d\\n", received_packets;
        printf "Packet Delivery Ratio (PDR): %.2f %%\\n", pdr;
        printf "Simulation Time: %.2f s\\n", simulation_time;
    } else {
        printf "No packets were sent.\\n";
    }
}
`;
